<?php  

// --------------------------------------------------------------------

if ( ! function_usable('pass_icon'))
{

    /**
     * Font Awesome 4.7 icons array
     * http://fontawesome.io/cheatsheet/
     * 
     * @version 4.7.0
     * @date 14.11.2016.
     * @param  integer $type      Determines the type response to return
     *                            1: Returns a select option <option></option>
     *                            2: Search for an icon and return it's matching key
     *                            4: Search for an icon and return it's matching value
     *                            Else: If the icon exists and returns a boolean
     * @param  string  $ic        The icon to search for, provide a name like fa-anchor or just part of it like anchor
     * @param  boolean $literal   Treats the search string literally instead of using the processed value
     * @return variable           Depending on the type, returns a string or boolean
    */
	function pass_icon($type, $ic = '', $literal = FALSE, $picker = false) 
    {
        $literal_ic = $ic;

        $all_icons = array (
            0 => 'fa-500px',
            1 => 'fa-address-book',
            2 => 'fa-address-book-o',
            3 => 'fa-address-card',
            4 => 'fa-address-card-o',
            5 => 'fa-adjust',
            6 => 'fa-adn',
            7 => 'fa-align-center',
            8 => 'fa-align-justify',
            9 => 'fa-align-left',
            10 => 'fa-align-right',
            11 => 'fa-amazon',
            12 => 'fa-ambulance',
            13 => 'fa-american-sign-language-interpreting',
            14 => 'fa-anchor',
            15 => 'fa-android',
            16 => 'fa-angellist',
            17 => 'fa-angle-double-down',
            18 => 'fa-angle-double-left',
            19 => 'fa-angle-double-right',
            20 => 'fa-angle-double-up',
            21 => 'fa-angle-down',
            22 => 'fa-angle-left',
            23 => 'fa-angle-right',
            24 => 'fa-angle-up',
            25 => 'fa-apple',
            26 => 'fa-archive',
            27 => 'fa-area-chart',
            28 => 'fa-arrow-circle-down',
            29 => 'fa-arrow-circle-left',
            30 => 'fa-arrow-circle-o-down',
            31 => 'fa-arrow-circle-o-left',
            32 => 'fa-arrow-circle-o-right',
            33 => 'fa-arrow-circle-o-up',
            34 => 'fa-arrow-circle-right',
            35 => 'fa-arrow-circle-up',
            36 => 'fa-arrow-down',
            37 => 'fa-arrow-left',
            38 => 'fa-arrow-right',
            39 => 'fa-arrow-up',
            40 => 'fa-arrows',
            41 => 'fa-arrows-alt',
            42 => 'fa-arrows-h',
            43 => 'fa-arrows-v',
            44 => 'fa-asl-interpreting',
            45 => 'fa-assistive-listening-systems',
            46 => 'fa-asterisk',
            47 => 'fa-at',
            48 => 'fa-audio-description',
            49 => 'fa-automobile',
            50 => 'fa-backward',
            51 => 'fa-balance-scale',
            52 => 'fa-ban',
            53 => 'fa-bandcamp',
            54 => 'fa-bank',
            55 => 'fa-bar-chart',
            56 => 'fa-bar-chart-o',
            57 => 'fa-barcode',
            58 => 'fa-bars',
            59 => 'fa-bath',
            60 => 'fa-bathtub',
            61 => 'fa-battery',
            62 => 'fa-battery-0',
            63 => 'fa-battery-1',
            64 => 'fa-battery-2',
            65 => 'fa-battery-3',
            66 => 'fa-battery-4',
            67 => 'fa-battery-empty',
            68 => 'fa-battery-full',
            69 => 'fa-battery-half',
            70 => 'fa-battery-quarter',
            71 => 'fa-battery-three-quarters',
            72 => 'fa-bed',
            73 => 'fa-beer',
            74 => 'fa-behance',
            75 => 'fa-behance-square',
            76 => 'fa-bell',
            77 => 'fa-bell-o',
            78 => 'fa-bell-slash',
            79 => 'fa-bell-slash-o',
            80 => 'fa-bicycle',
            81 => 'fa-binoculars',
            82 => 'fa-birthday-cake',
            83 => 'fa-bitbucket',
            84 => 'fa-bitbucket-square',
            85 => 'fa-bitcoin',
            86 => 'fa-black-tie',
            87 => 'fa-blind',
            88 => 'fa-bluetooth',
            89 => 'fa-bluetooth-b',
            90 => 'fa-bold',
            91 => 'fa-bolt',
            92 => 'fa-bomb',
            93 => 'fa-book',
            94 => 'fa-bookmark',
            95 => 'fa-bookmark-o',
            96 => 'fa-braille',
            97 => 'fa-briefcase',
            98 => 'fa-btc',
            99 => 'fa-bug',
            100 => 'fa-building',
            101 => 'fa-building-o',
            102 => 'fa-bullhorn',
            103 => 'fa-bullseye',
            104 => 'fa-bus',
            105 => 'fa-buysellads',
            106 => 'fa-cab',
            107 => 'fa-calculator',
            108 => 'fa-calendar',
            109 => 'fa-calendar-check-o',
            110 => 'fa-calendar-minus-o',
            111 => 'fa-calendar-o',
            112 => 'fa-calendar-plus-o',
            113 => 'fa-calendar-times-o',
            114 => 'fa-camera',
            115 => 'fa-camera-retro',
            116 => 'fa-car',
            117 => 'fa-caret-down',
            118 => 'fa-caret-left',
            119 => 'fa-caret-right',
            120 => 'fa-caret-square-o-down',
            121 => 'fa-caret-square-o-left',
            122 => 'fa-caret-square-o-right',
            123 => 'fa-caret-square-o-up',
            124 => 'fa-caret-up',
            125 => 'fa-cart-arrow-down',
            126 => 'fa-cart-plus',
            127 => 'fa-cc',
            128 => 'fa-cc-amex',
            129 => 'fa-cc-diners-club',
            130 => 'fa-cc-discover',
            131 => 'fa-cc-jcb',
            132 => 'fa-cc-mastercard',
            133 => 'fa-cc-paypal',
            134 => 'fa-cc-stripe',
            135 => 'fa-cc-visa',
            136 => 'fa-certificate',
            137 => 'fa-chain',
            138 => 'fa-chain-broken',
            139 => 'fa-check',
            140 => 'fa-check-circle',
            141 => 'fa-check-circle-o',
            142 => 'fa-check-square',
            143 => 'fa-check-square-o',
            144 => 'fa-chevron-circle-down',
            145 => 'fa-chevron-circle-left',
            146 => 'fa-chevron-circle-right',
            147 => 'fa-chevron-circle-up',
            148 => 'fa-chevron-down',
            149 => 'fa-chevron-left',
            150 => 'fa-chevron-right',
            151 => 'fa-chevron-up',
            152 => 'fa-child',
            153 => 'fa-chrome',
            154 => 'fa-circle',
            155 => 'fa-circle-o',
            156 => 'fa-circle-o-notch',
            157 => 'fa-circle-thin',
            158 => 'fa-clipboard',
            159 => 'fa-clock-o',
            160 => 'fa-clone',
            161 => 'fa-close',
            162 => 'fa-cloud',
            163 => 'fa-cloud-download',
            164 => 'fa-cloud-upload',
            165 => 'fa-cny',
            166 => 'fa-code',
            167 => 'fa-code-fork',
            168 => 'fa-codepen',
            169 => 'fa-codiepie',
            170 => 'fa-coffee',
            171 => 'fa-cog',
            172 => 'fa-cogs',
            173 => 'fa-columns',
            174 => 'fa-comment',
            175 => 'fa-comment-o',
            176 => 'fa-commenting',
            177 => 'fa-commenting-o',
            178 => 'fa-comments',
            179 => 'fa-comments-o',
            180 => 'fa-compass',
            181 => 'fa-compress',
            182 => 'fa-connectdevelop',
            183 => 'fa-contao',
            184 => 'fa-copy',
            185 => 'fa-copyright',
            186 => 'fa-creative-commons',
            187 => 'fa-credit-card',
            188 => 'fa-credit-card-alt',
            189 => 'fa-crop',
            190 => 'fa-crosshairs',
            191 => 'fa-css3',
            192 => 'fa-cube',
            193 => 'fa-cubes',
            194 => 'fa-cut',
            195 => 'fa-cutlery',
            196 => 'fa-dashboard',
            197 => 'fa-dashcube',
            198 => 'fa-database',
            199 => 'fa-deaf',
            200 => 'fa-deafness',
            201 => 'fa-dedent',
            202 => 'fa-delicious',
            203 => 'fa-desktop',
            204 => 'fa-deviantart',
            205 => 'fa-diamond',
            206 => 'fa-digg',
            207 => 'fa-dollar',
            208 => 'fa-dot-circle-o',
            209 => 'fa-download',
            210 => 'fa-dribbble',
            211 => 'fa-drivers-license',
            212 => 'fa-drivers-license-o',
            213 => 'fa-dropbox',
            214 => 'fa-drupal',
            215 => 'fa-edge',
            216 => 'fa-edit',
            217 => 'fa-eercast',
            218 => 'fa-eject',
            219 => 'fa-ellipsis-h',
            220 => 'fa-ellipsis-v',
            221 => 'fa-empire',
            222 => 'fa-envelope',
            223 => 'fa-envelope-o',
            224 => 'fa-envelope-open',
            225 => 'fa-envelope-open-o',
            226 => 'fa-envelope-square',
            227 => 'fa-envira',
            228 => 'fa-eraser',
            229 => 'fa-etsy',
            230 => 'fa-eur',
            231 => 'fa-euro',
            232 => 'fa-exchange',
            233 => 'fa-exclamation',
            234 => 'fa-exclamation-circle',
            235 => 'fa-exclamation-triangle',
            236 => 'fa-expand',
            237 => 'fa-expeditedssl',
            238 => 'fa-external-link',
            239 => 'fa-external-link-square',
            240 => 'fa-eye',
            241 => 'fa-eye-slash',
            242 => 'fa-eyedropper',
            243 => 'fa-fa',
            244 => 'fa-facebook',
            245 => 'fa-facebook-f',
            246 => 'fa-facebook-official',
            247 => 'fa-facebook-square',
            248 => 'fa-fast-backward',
            249 => 'fa-fast-forward',
            250 => 'fa-fax',
            251 => 'fa-feed',
            252 => 'fa-female',
            253 => 'fa-fighter-jet',
            254 => 'fa-file',
            255 => 'fa-file-archive-o',
            256 => 'fa-file-audio-o',
            257 => 'fa-file-code-o',
            258 => 'fa-file-excel-o',
            259 => 'fa-file-image-o',
            260 => 'fa-file-movie-o',
            261 => 'fa-file-o',
            262 => 'fa-file-pdf-o',
            263 => 'fa-file-photo-o',
            264 => 'fa-file-picture-o',
            265 => 'fa-file-powerpoint-o',
            266 => 'fa-file-sound-o',
            267 => 'fa-file-text',
            268 => 'fa-file-text-o',
            269 => 'fa-file-video-o',
            270 => 'fa-file-word-o',
            271 => 'fa-file-zip-o',
            272 => 'fa-files-o',
            273 => 'fa-film',
            274 => 'fa-filter',
            275 => 'fa-fire',
            276 => 'fa-fire-extinguisher',
            277 => 'fa-firefox',
            278 => 'fa-first-order',
            279 => 'fa-flag',
            280 => 'fa-flag-checkered',
            281 => 'fa-flag-o',
            282 => 'fa-flash',
            283 => 'fa-flask',
            284 => 'fa-flickr',
            285 => 'fa-floppy-o',
            286 => 'fa-folder',
            287 => 'fa-folder-o',
            288 => 'fa-folder-open',
            289 => 'fa-folder-open-o',
            290 => 'fa-font',
            291 => 'fa-font-awesome',
            292 => 'fa-fonticons',
            293 => 'fa-fort-awesome',
            294 => 'fa-forumbee',
            295 => 'fa-forward',
            296 => 'fa-foursquare',
            297 => 'fa-free-code-camp',
            298 => 'fa-frown-o',
            299 => 'fa-futbol-o',
            300 => 'fa-gamepad',
            301 => 'fa-gavel',
            302 => 'fa-gbp',
            303 => 'fa-ge',
            304 => 'fa-gear',
            305 => 'fa-gears',
            306 => 'fa-genderless',
            307 => 'fa-get-pocket',
            308 => 'fa-gg',
            309 => 'fa-gg-circle',
            310 => 'fa-gift',
            311 => 'fa-git',
            312 => 'fa-git-square',
            313 => 'fa-github',
            314 => 'fa-github-alt',
            315 => 'fa-github-square',
            316 => 'fa-gitlab',
            317 => 'fa-gittip',
            318 => 'fa-glass',
            319 => 'fa-glide',
            320 => 'fa-glide-g',
            321 => 'fa-globe',
            322 => 'fa-google',
            323 => 'fa-google-plus',
            324 => 'fa-google-plus-circle',
            325 => 'fa-google-plus-official',
            326 => 'fa-google-plus-square',
            327 => 'fa-google-wallet',
            328 => 'fa-graduation-cap',
            329 => 'fa-gratipay',
            330 => 'fa-grav',
            331 => 'fa-group',
            332 => 'fa-h-square',
            333 => 'fa-hacker-news',
            334 => 'fa-hand-grab-o',
            335 => 'fa-hand-lizard-o',
            336 => 'fa-hand-o-down',
            337 => 'fa-hand-o-left',
            338 => 'fa-hand-o-right',
            339 => 'fa-hand-o-up',
            340 => 'fa-hand-paper-o',
            341 => 'fa-hand-peace-o',
            342 => 'fa-hand-pointer-o',
            343 => 'fa-hand-rock-o',
            344 => 'fa-hand-scissors-o',
            345 => 'fa-hand-spock-o',
            346 => 'fa-hand-stop-o',
            347 => 'fa-handshake-o',
            348 => 'fa-hard-of-hearing',
            349 => 'fa-hashtag',
            350 => 'fa-hdd-o',
            351 => 'fa-header',
            352 => 'fa-headphones',
            353 => 'fa-heart',
            354 => 'fa-heart-o',
            355 => 'fa-heartbeat',
            356 => 'fa-history',
            357 => 'fa-home',
            358 => 'fa-hospital-o',
            359 => 'fa-hotel',
            360 => 'fa-hourglass',
            361 => 'fa-hourglass-1',
            362 => 'fa-hourglass-2',
            363 => 'fa-hourglass-3',
            364 => 'fa-hourglass-end',
            365 => 'fa-hourglass-half',
            366 => 'fa-hourglass-o',
            367 => 'fa-hourglass-start',
            368 => 'fa-houzz',
            369 => 'fa-html5',
            370 => 'fa-i-cursor',
            371 => 'fa-id-badge',
            372 => 'fa-id-card',
            373 => 'fa-id-card-o',
            374 => 'fa-ils',
            375 => 'fa-image',
            376 => 'fa-imdb',
            377 => 'fa-inbox',
            378 => 'fa-indent',
            379 => 'fa-industry',
            380 => 'fa-info',
            381 => 'fa-info-circle',
            382 => 'fa-inr',
            383 => 'fa-instagram',
            384 => 'fa-institution',
            385 => 'fa-internet-explorer',
            386 => 'fa-intersex',
            387 => 'fa-ioxhost',
            388 => 'fa-italic',
            389 => 'fa-joomla',
            390 => 'fa-jpy',
            391 => 'fa-jsfiddle',
            392 => 'fa-key',
            393 => 'fa-keyboard-o',
            394 => 'fa-krw',
            395 => 'fa-language',
            396 => 'fa-laptop',
            397 => 'fa-lastfm',
            398 => 'fa-lastfm-square',
            399 => 'fa-leaf',
            400 => 'fa-leanpub',
            401 => 'fa-legal',
            402 => 'fa-lemon-o',
            403 => 'fa-level-down',
            404 => 'fa-level-up',
            405 => 'fa-life-bouy',
            406 => 'fa-life-buoy',
            407 => 'fa-life-ring',
            408 => 'fa-life-saver',
            409 => 'fa-lightbulb-o',
            410 => 'fa-line-chart',
            411 => 'fa-link',
            412 => 'fa-linkedin',
            413 => 'fa-linkedin-square',
            414 => 'fa-linode',
            415 => 'fa-linux',
            416 => 'fa-list',
            417 => 'fa-list-alt',
            418 => 'fa-list-ol',
            419 => 'fa-list-ul',
            420 => 'fa-location-arrow',
            421 => 'fa-lock',
            422 => 'fa-long-arrow-down',
            423 => 'fa-long-arrow-left',
            424 => 'fa-long-arrow-right',
            425 => 'fa-long-arrow-up',
            426 => 'fa-low-vision',
            427 => 'fa-magic',
            428 => 'fa-magnet',
            429 => 'fa-mail-forward',
            430 => 'fa-mail-reply',
            431 => 'fa-mail-reply-all',
            432 => 'fa-male',
            433 => 'fa-map',
            434 => 'fa-map-marker',
            435 => 'fa-map-o',
            436 => 'fa-map-pin',
            437 => 'fa-map-signs',
            438 => 'fa-mars',
            439 => 'fa-mars-double',
            440 => 'fa-mars-stroke',
            441 => 'fa-mars-stroke-h',
            442 => 'fa-mars-stroke-v',
            443 => 'fa-maxcdn',
            444 => 'fa-meanpath',
            445 => 'fa-medium',
            446 => 'fa-medkit',
            447 => 'fa-meetup',
            448 => 'fa-meh-o',
            449 => 'fa-mercury',
            450 => 'fa-microchip',
            451 => 'fa-microphone',
            452 => 'fa-microphone-slash',
            453 => 'fa-minus',
            454 => 'fa-minus-circle',
            455 => 'fa-minus-square',
            456 => 'fa-minus-square-o',
            457 => 'fa-mixcloud',
            458 => 'fa-mobile',
            459 => 'fa-mobile-phone',
            460 => 'fa-modx',
            461 => 'fa-money',
            462 => 'fa-moon-o',
            463 => 'fa-mortar-board',
            464 => 'fa-motorcycle',
            465 => 'fa-mouse-pointer',
            466 => 'fa-music',
            467 => 'fa-navicon',
            468 => 'fa-neuter',
            469 => 'fa-newspaper-o',
            470 => 'fa-object-group',
            471 => 'fa-object-ungroup',
            472 => 'fa-odnoklassniki',
            473 => 'fa-odnoklassniki-square',
            474 => 'fa-opencart',
            475 => 'fa-openid',
            476 => 'fa-opera',
            477 => 'fa-optin-monster',
            478 => 'fa-outdent',
            479 => 'fa-pagelines',
            480 => 'fa-paint-brush',
            481 => 'fa-paper-plane',
            482 => 'fa-paper-plane-o',
            483 => 'fa-paperclip',
            484 => 'fa-paragraph',
            485 => 'fa-paste',
            486 => 'fa-pause',
            487 => 'fa-pause-circle',
            488 => 'fa-pause-circle-o',
            489 => 'fa-paw',
            490 => 'fa-paypal',
            491 => 'fa-pencil',
            492 => 'fa-pencil-square',
            493 => 'fa-pencil-square-o',
            494 => 'fa-percent',
            495 => 'fa-phone',
            496 => 'fa-phone-square',
            497 => 'fa-photo',
            498 => 'fa-picture-o',
            499 => 'fa-pie-chart',
            500 => 'fa-pied-piper',
            501 => 'fa-pied-piper-alt',
            502 => 'fa-pied-piper-pp',
            503 => 'fa-pinterest',
            504 => 'fa-pinterest-p',
            505 => 'fa-pinterest-square',
            506 => 'fa-plane',
            507 => 'fa-play',
            508 => 'fa-play-circle',
            509 => 'fa-play-circle-o',
            510 => 'fa-plug',
            511 => 'fa-plus',
            512 => 'fa-plus-circle',
            513 => 'fa-plus-square',
            514 => 'fa-plus-square-o',
            515 => 'fa-podcast',
            516 => 'fa-power-off',
            517 => 'fa-print',
            518 => 'fa-product-hunt',
            519 => 'fa-puzzle-piece',
            520 => 'fa-qq',
            521 => 'fa-qrcode',
            522 => 'fa-question',
            523 => 'fa-question-circle',
            524 => 'fa-question-circle-o',
            525 => 'fa-quora',
            526 => 'fa-quote-left',
            527 => 'fa-quote-right',
            528 => 'fa-ra',
            529 => 'fa-random',
            530 => 'fa-ravelry',
            531 => 'fa-rebel',
            532 => 'fa-recycle',
            533 => 'fa-reddit',
            534 => 'fa-reddit-alien',
            535 => 'fa-reddit-square',
            536 => 'fa-refresh',
            537 => 'fa-registered',
            538 => 'fa-remove',
            539 => 'fa-renren',
            540 => 'fa-reorder',
            541 => 'fa-repeat',
            542 => 'fa-reply',
            543 => 'fa-reply-all',
            544 => 'fa-resistance',
            545 => 'fa-retweet',
            546 => 'fa-rmb',
            547 => 'fa-road',
            548 => 'fa-rocket',
            549 => 'fa-rotate-left',
            550 => 'fa-rotate-right',
            551 => 'fa-rouble',
            552 => 'fa-rss',
            553 => 'fa-rss-square',
            554 => 'fa-rub',
            555 => 'fa-ruble',
            556 => 'fa-rupee',
            557 => 'fa-s15',
            558 => 'fa-safari',
            559 => 'fa-save',
            560 => 'fa-scissors',
            561 => 'fa-scribd',
            562 => 'fa-search',
            563 => 'fa-search-minus',
            564 => 'fa-search-plus',
            565 => 'fa-sellsy',
            566 => 'fa-send',
            567 => 'fa-send-o',
            568 => 'fa-server',
            569 => 'fa-share',
            570 => 'fa-share-alt',
            571 => 'fa-share-alt-square',
            572 => 'fa-share-square',
            573 => 'fa-share-square-o',
            574 => 'fa-shekel',
            575 => 'fa-sheqel',
            576 => 'fa-shield',
            577 => 'fa-ship',
            578 => 'fa-shirtsinbulk',
            579 => 'fa-shopping-bag',
            580 => 'fa-shopping-basket',
            581 => 'fa-shopping-cart',
            582 => 'fa-shower',
            583 => 'fa-sign-in',
            584 => 'fa-sign-language',
            585 => 'fa-sign-out',
            586 => 'fa-signal',
            587 => 'fa-signing',
            588 => 'fa-simplybuilt',
            589 => 'fa-sitemap',
            590 => 'fa-skyatlas',
            591 => 'fa-skype',
            592 => 'fa-slack',
            593 => 'fa-sliders',
            594 => 'fa-slideshare',
            595 => 'fa-smile-o',
            596 => 'fa-snapchat',
            597 => 'fa-snapchat-ghost',
            598 => 'fa-snapchat-square',
            599 => 'fa-snowflake-o',
            600 => 'fa-soccer-ball-o',
            601 => 'fa-sort',
            602 => 'fa-sort-alpha-asc',
            603 => 'fa-sort-alpha-desc',
            604 => 'fa-sort-amount-asc',
            605 => 'fa-sort-amount-desc',
            606 => 'fa-sort-asc',
            607 => 'fa-sort-desc',
            608 => 'fa-sort-down',
            609 => 'fa-sort-numeric-asc',
            610 => 'fa-sort-numeric-desc',
            611 => 'fa-sort-up',
            612 => 'fa-soundcloud',
            613 => 'fa-space-shuttle',
            614 => 'fa-spinner',
            615 => 'fa-spoon',
            616 => 'fa-spotify',
            617 => 'fa-square',
            618 => 'fa-square-o',
            619 => 'fa-stack-exchange',
            620 => 'fa-stack-overflow',
            621 => 'fa-star',
            622 => 'fa-star-half',
            623 => 'fa-star-half-empty',
            624 => 'fa-star-half-full',
            625 => 'fa-star-half-o',
            626 => 'fa-star-o',
            627 => 'fa-steam',
            628 => 'fa-steam-square',
            629 => 'fa-step-backward',
            630 => 'fa-step-forward',
            631 => 'fa-stethoscope',
            632 => 'fa-sticky-note',
            633 => 'fa-sticky-note-o',
            634 => 'fa-stop',
            635 => 'fa-stop-circle',
            636 => 'fa-stop-circle-o',
            637 => 'fa-street-view',
            638 => 'fa-strikethrough',
            639 => 'fa-stumbleupon',
            640 => 'fa-stumbleupon-circle',
            641 => 'fa-subscript',
            642 => 'fa-subway',
            643 => 'fa-suitcase',
            644 => 'fa-sun-o',
            645 => 'fa-superpowers',
            646 => 'fa-superscript',
            647 => 'fa-support',
            648 => 'fa-table',
            649 => 'fa-tablet',
            650 => 'fa-tachometer',
            651 => 'fa-tag',
            652 => 'fa-tags',
            653 => 'fa-tasks',
            654 => 'fa-taxi',
            655 => 'fa-telegram',
            656 => 'fa-television',
            657 => 'fa-tencent-weibo',
            658 => 'fa-terminal',
            659 => 'fa-text-height',
            660 => 'fa-text-width',
            661 => 'fa-th',
            662 => 'fa-th-large',
            663 => 'fa-th-list',
            664 => 'fa-themeisle',
            665 => 'fa-thermometer',
            666 => 'fa-thermometer-0',
            667 => 'fa-thermometer-1',
            668 => 'fa-thermometer-2',
            669 => 'fa-thermometer-3',
            670 => 'fa-thermometer-4',
            671 => 'fa-thermometer-empty',
            672 => 'fa-thermometer-full',
            673 => 'fa-thermometer-half',
            674 => 'fa-thermometer-quarter',
            675 => 'fa-thermometer-three-quarters',
            676 => 'fa-thumb-tack',
            677 => 'fa-thumbs-down',
            678 => 'fa-thumbs-o-down',
            679 => 'fa-thumbs-o-up',
            680 => 'fa-thumbs-up',
            681 => 'fa-ticket',
            682 => 'fa-times',
            683 => 'fa-times-circle',
            684 => 'fa-times-circle-o',
            685 => 'fa-times-rectangle',
            686 => 'fa-times-rectangle-o',
            687 => 'fa-tint',
            688 => 'fa-toggle-down',
            689 => 'fa-toggle-left',
            690 => 'fa-toggle-off',
            691 => 'fa-toggle-on',
            692 => 'fa-toggle-right',
            693 => 'fa-toggle-up',
            694 => 'fa-trademark',
            695 => 'fa-train',
            696 => 'fa-transgender',
            697 => 'fa-transgender-alt',
            698 => 'fa-trash',
            699 => 'fa-trash-o',
            700 => 'fa-tree',
            701 => 'fa-trello',
            702 => 'fa-tripadvisor',
            703 => 'fa-trophy',
            704 => 'fa-truck',
            705 => 'fa-try',
            706 => 'fa-tty',
            707 => 'fa-tumblr',
            708 => 'fa-tumblr-square',
            709 => 'fa-turkish-lira',
            710 => 'fa-tv',
            711 => 'fa-twitch',
            712 => 'fa-twitter',
            713 => 'fa-twitter-square',
            714 => 'fa-umbrella',
            715 => 'fa-underline',
            716 => 'fa-undo',
            717 => 'fa-universal-access',
            718 => 'fa-university',
            719 => 'fa-unlink',
            720 => 'fa-unlock',
            721 => 'fa-unlock-alt',
            722 => 'fa-unsorted',
            723 => 'fa-upload',
            724 => 'fa-usb',
            725 => 'fa-usd',
            726 => 'fa-user',
            727 => 'fa-user-circle',
            728 => 'fa-user-circle-o',
            729 => 'fa-user-md',
            730 => 'fa-user-o',
            731 => 'fa-user-plus',
            732 => 'fa-user-secret',
            733 => 'fa-user-times',
            734 => 'fa-users',
            735 => 'fa-vcard',
            736 => 'fa-vcard-o',
            737 => 'fa-venus',
            738 => 'fa-venus-double',
            739 => 'fa-venus-mars',
            740 => 'fa-viacoin',
            741 => 'fa-viadeo',
            742 => 'fa-viadeo-square',
            743 => 'fa-video-camera',
            744 => 'fa-vimeo',
            745 => 'fa-vimeo-square',
            746 => 'fa-vine',
            747 => 'fa-vk',
            748 => 'fa-volume-control-phone',
            749 => 'fa-volume-down',
            750 => 'fa-volume-off',
            751 => 'fa-volume-up',
            752 => 'fa-warning',
            753 => 'fa-wechat',
            754 => 'fa-weibo',
            755 => 'fa-weixin',
            756 => 'fa-whatsapp',
            757 => 'fa-wheelchair',
            758 => 'fa-wheelchair-alt',
            759 => 'fa-wifi',
            760 => 'fa-wikipedia-w',
            761 => 'fa-window-close',
            762 => 'fa-window-close-o',
            763 => 'fa-window-maximize',
            764 => 'fa-window-minimize',
            765 => 'fa-window-restore',
            766 => 'fa-windows',
            767 => 'fa-won',
            768 => 'fa-wordpress',
            769 => 'fa-wpbeginner',
            770 => 'fa-wpexplorer',
            771 => 'fa-wpforms',
            772 => 'fa-wrench',
            773 => 'fa-xing',
            774 => 'fa-xing-square',
            775 => 'fa-y-combinator',
            776 => 'fa-y-combinator-square',
            777 => 'fa-yahoo',
            778 => 'fa-yc',
            779 => 'fa-yc-square',
            780 => 'fa-yelp',
            781 => 'fa-yen',
            782 => 'fa-yoast',
            783 => 'fa-youtube',
            784 => 'fa-youtube-play',
            785 => 'fa-youtube-square',
            // New Icons
            786 => 'fa-chart-area',
            787 => 'fa-chart-bar',
            788 => 'fa-chart-line',
            789 => 'fa-chart-pie',
        );

        $all_icons = array ( 
            'fa-address-book', 
            'fa-address-card', 
            'fa-adjust', 
            'fa-align-center',
            'fa-align-justify',
            'fa-align-left',
            'fa-align-right', 
            'fa-ambulance',
            'fa-american-sign-language-interpreting',
            'fa-anchor',  
            'fa-angle-double-down',
            'fa-angle-double-left',
            'fa-angle-double-right',
            'fa-angle-double-up',
            'fa-angle-down',
            'fa-angle-left',
            'fa-angle-right',
            'fa-angle-up', 
            'fa-angry', 
            'fa-archive', 
            'fa-arrow-circle-down',
            'fa-arrow-circle-left', 
            'fa-arrow-alt-circle-down',
            'fa-arrow-alt-circle-left', 
            'fa-arrow-alt-circle-right',
            'fa-arrow-alt-circle-up', 
            'fa-arrow-down',
            'fa-arrow-left',
            'fa-arrow-right',
            'fa-arrow-up', 
            'fa-arrows-alt',   
            'fa-assistive-listening-systems',
            'fa-asterisk',
            'fa-at',
            'fa-audio-description', 
            'fa-backward',
            'fa-balance-scale',
            'fa-ban', 
            'fa-barcode',
            'fa-bars',
            'fa-bath', 
            'fa-battery-empty',
            'fa-battery-full',
            'fa-battery-half',
            'fa-battery-quarter',
            'fa-battery-three-quarters',
            'fa-bed',
            'fa-beer', 
            'fa-bell', 
            'fa-bell-slash', 
            'fa-bicycle',
            'fa-binoculars',
            'fa-birthday-cake', 
            'fa-blind', 
            'fa-bold',
            'fa-bolt',
            'fa-bomb',
            'fa-book',
            'fa-bookmark', 
            'fa-braille',
            'fa-briefcase', 
            'fa-bug',
            'fa-building', 
            'fa-bullhorn',
            'fa-bullseye',
            'fa-bus', 
            'fa-calculator',
            'fa-calendar', 
            'fa-calendar-alt', 
            'fa-calendar-check', 
            'fa-calendar-minus', 
            'fa-calendar-plus', 
            'fa-calendar-times', 
            'fa-camera',
            'fa-camera-retro',
            'fa-car',
            'fa-caret-down',
            'fa-caret-left',
            'fa-caret-square-down',
            'fa-caret-right', 
            'fa-caret-up',
            'fa-cart-arrow-down',
            'fa-cart-plus', 
            'fa-certificate', 
            'fa-chart-area',
            'fa-chart-bar',
            'fa-chart-line',
            'fa-chart-pie',
            'fa-check',
            'fa-check-circle', 
            'fa-check-square', 
            'fa-chevron-circle-down',
            'fa-chevron-circle-left',
            'fa-chevron-circle-right',
            'fa-chevron-circle-up',
            'fa-chevron-down',
            'fa-chevron-left',
            'fa-chevron-right',
            'fa-chevron-up',
            'fa-child', 
            'fa-circle', 
            'fa-clipboard', 
            'fa-clone',   
            'fa-code',  
            'fa-coffee',
            'fa-cog',
            'fa-cogs',
            'fa-columns',
            'fa-comment', 
            'fa-comments', 
            'fa-compass',
            'fa-compress', 
            'fa-copy',
            'fa-copyright', 
            'fa-credit-card', 
            'fa-crop',
            'fa-crosshairs', 
            'fa-cube',
            'fa-cubes',
            'fa-cut', 
            'fa-database',
            'fa-deaf', 
            'fa-desktop', 
            'fa-download',  
            'fa-edit', 
            'fa-eject',
            'fa-ellipsis-h',
            'fa-ellipsis-v', 
            'fa-envelope-square', 
            'fa-eraser', 
            'fa-exclamation',
            'fa-exclamation-circle',
            'fa-exclamation-triangle',
            'fa-expand', 
            'fa-eye',
            'fa-eye-slash', 
            'fa-fax', 
            'fa-female',
            'fa-fighter-jet',  
            'fa-film',
            'fa-filter',
            'fa-fire',
            'fa-fire-extinguisher', 
            'fa-flag',
            'fa-flag-checkered', 
            'fa-flask', 
            'fa-folder', 
            'fa-folder-open',  
            'fa-font', 
            'fa-forward', 
            'fa-gamepad',
            'fa-gavel', 
            'fa-genderless', 
            'fa-gift', 
            'fa-globe', 
            'fa-graduation-cap', 
            'fa-h-square',  
            'fa-hashtag', 
            'fa-headphones',
            'fa-heart', 
            'fa-heartbeat',
            'fa-history',
            'fa-home', 
            'fa-hotel',
            'fa-hourglass', 
            'fa-hourglass-end',
            'fa-hourglass-half', 
            'fa-hourglass-start', 
            'fa-i-cursor',
            'fa-id-badge',
            'fa-id-card', 
            'fa-image', 
            'fa-inbox',
            'fa-indent',
            'fa-industry',
            'fa-info',
            'fa-info-circle', 
            'fa-italic', 
            'fa-key', 
            'fa-language',
            'fa-laptop', 
            'fa-leaf',  
            'fa-life-ring', 
            'fa-link', 
            'fa-list',
            'fa-list-alt',
            'fa-list-ol',
            'fa-list-ul', 
            'fa-low-vision',
            'fa-magic',
            'fa-magnet',  
            'fa-male',
            'fa-map',
            'fa-map-marker', 
            'fa-map-pin',
            'fa-map-signs',
            'fa-mars',
            'fa-mars-double',
            'fa-mars-stroke',
            'fa-mars-stroke-h',
            'fa-mars-stroke-v', 
            'fa-medkit', 
            'fa-mercury',
            'fa-microchip',
            'fa-microphone',
            'fa-microphone-slash',
            'fa-minus',
            'fa-minus-circle',
            'fa-minus-square', 
            'fa-mobile', 
            'fa-motorcycle',
            'fa-mouse-pointer',
            'fa-music', 
            'fa-neuter', 
            'fa-object-group',
            'fa-object-ungroup', 
            'fa-outdent', 
            'fa-paint-brush',
            'fa-paper-plane', 
            'fa-paperclip',
            'fa-paragraph',
            'fa-paste',
            'fa-pause',
            'fa-pause-circle', 
            'fa-paw', 
            'fa-percent',
            'fa-phone',
            'fa-phone-square', 
            'fa-plane',
            'fa-play',
            'fa-play-circle', 
            'fa-plug',
            'fa-plus',
            'fa-plus-circle',
            'fa-plus-square', 
            'fa-podcast',
            'fa-power-off',
            'fa-print', 
            'fa-puzzle-piece', 
            'fa-qrcode',
            'fa-question',
            'fa-question-circle', 
            'fa-quote-left',
            'fa-quote-right', 
            'fa-random', 
            'fa-recycle', 
            'fa-registered', 
            'fa-reply',
            'fa-reply-all', 
            'fa-retweet', 
            'fa-road',
            'fa-rocket',  
            'fa-rss',
            'fa-rss-square',  
            'fa-save', 
            'fa-search',
            'fa-search-minus',
            'fa-search-plus', 
            'fa-server',
            'fa-share',
            'fa-share-alt',
            'fa-share-alt-square',
            'fa-share-square',  
            'fa-shopping-bag',
            'fa-shopping-basket',
            'fa-shopping-cart',
            'fa-shower', 
            'fa-sign-language', 
            'fa-signal', 
            'fa-sitemap', 
            'fa-sort', 
            'fa-sort-down', 
            'fa-sort-up', 
            'fa-space-shuttle',
            'fa-spinner', 
            'fa-square', 
            'fa-star',
            'fa-star-half', 
            'fa-step-backward',
            'fa-step-forward',
            'fa-stethoscope',
            'fa-sticky-note', 
            'fa-stop',
            'fa-stop-circle', 
            'fa-street-view',
            'fa-strikethrough', 
            'fa-subscript',
            'fa-subway',
            'fa-suitcase', 
            'fa-superscript', 
            'fa-table',
            'fa-tablet', 
            'fa-tag',
            'fa-tags',
            'fa-tasks',
            'fa-taxi', 
            'fa-terminal',
            'fa-text-height',
            'fa-text-width',
            'fa-th',
            'fa-th-large',
            'fa-th-list', 
            'fa-thermometer',  
            'fa-thermometer-empty',
            'fa-thermometer-full',
            'fa-thermometer-half',
            'fa-thermometer-quarter',
            'fa-thermometer-three-quarters', 
            'fa-thumbs-down', 
            'fa-thumbs-up', 
            'fa-times',
            'fa-times-circle', 
            'fa-tint', 
            'fa-toggle-off',
            'fa-toggle-on', 
            'fa-trademark',
            'fa-train',
            'fa-transgender',
            'fa-transgender-alt',
            'fa-trash', 
            'fa-tree', 
            'fa-trophy',
            'fa-truck', 
            'fa-tty', 
            'fa-tv', 
            'fa-umbrella',
            'fa-underline',
            'fa-undo',
            'fa-universal-access',
            'fa-university',
            'fa-unlink',
            'fa-unlock',
            'fa-unlock-alt', 
            'fa-upload', 
            'fa-user',
            'fa-user-circle', 
            'fa-user-md', 
            'fa-user-plus',
            'fa-user-secret',
            'fa-user-times',
            'fa-users', 
            'fa-venus',
            'fa-venus-double',
            'fa-venus-mars',  
            'fa-vimeo', 
            'fa-volume-down',
            'fa-volume-off',
            'fa-volume-up', 
            'fa-wheelchair', 
            'fa-wifi', 
            'fa-window-close', 
            'fa-window-maximize',
            'fa-window-minimize',
            'fa-window-restore',  
            'fa-wrench', 
            'fa-youtube-square', 
        );
 
        // Find the particular icon
        $ic = str_replace('fa fa-', '', $ic) ;
        $ic = str_replace($ic, 'fa-'.$ic, $ic);
        $search = $ic; 

        $icon = array_search($search, $all_icons, true);

        if ($icon) 
        {
            $icon_key = $icon;
        } 
        elseif (isset($all_icons[$ic])) 
        {
            $icon = pass_icon(3, $all_icons[$ic]);
            $icon_key = pass_icon(2, $icon);
        } 
        else 
        {
            $icon_key = array_search($ic, $all_icons, true);
        }

        if ($icon_key) 
        {
            $icon_key = $icon_key;
        } 
        else 
        {
            $icon_key = 99;
        }      

        if ($icon_key) 
        {
            $icon_value = $all_icons[$icon_key];
        } 
        else 
        {
            $icon_value = '';
        }

        $icon_t = ucfirst(str_replace('fa-', '', $icon_value)); 
        $icon_title = ucfirst(str_replace('-', ' ', $icon_t)); 

          // Generate select options for icons
        if($type == 1) 
        {
            $rows = '';
            foreach($all_icons as $key => $name) 
            {
                $icon_t_ = ucfirst(str_replace('fa-', '', $name)); 
                $icon_title = ucfirst(str_replace('-', ' ', $icon_t_)); 
                $name = 'fa '.$name;

                if(($literal === TRUE ? $literal_ic : $ic) == $name) 
                {
                    $selected = ' selected="selected"';
                } 
                else 
                {
                    $selected = '';
                }

                $rows .= '
                    <option value="'.$name.'"'.$selected.'>'. ($picker === true ? $name : $icon_title) ."</option>";
            }

            $rows .= "\n";

            return $rows;
        } 
        elseif($type == 2)
        {
            foreach($all_icons as $key => $name) 
            {
                if($icon_value == $name) 
                {
                    return $key;
                } 
            }
        } 
        elseif($type == 3) 
        {
            return $icon_value;
        } 
        elseif($type == 4) 
        {
            return '<i class="fa '.$icon_value.'"></i>';
        } 
        elseif($type == 5) 
        {
            return $all_icons;
        } 
        else 
        { 
            if(in_array($icon_value, $all_icons)) 
            {
                return 1;
            }
        }
	}
}

// --------------------------------------------------------------------

if ( ! function_usable('font_awesome'))
{
    /**
     * Returns a list of icons for the desired type. 
     * Supported values: "all" (default) | "brands" | "light" | "regular" | "solid" | "duotone"
     * At the time of writing this function, current version is 5.12.0.
     */

    function font_awesome($type = "all") 
    {
        $fa     = array();

        $brands = array( 
            "fa-500px",
            "fa-accessible-icon",
            "fa-accusoft",
            "fa-acquisitions-incorporated",
            "fa-adn",
            "fa-adobe",
            "fa-adversal",
            "fa-affiliatetheme",
            "fa-airbnb",
            "fa-algolia",
            "fa-alipay",
            "fa-amazon",
            "fa-amazon-pay",
            "fa-amilia",
            "fa-android",
            "fa-angellist",
            "fa-angrycreative",
            "fa-angular",
            "fa-app-store",
            "fa-app-store-ios",
            "fa-apper",
            "fa-apple",
            "fa-apple-pay",
            "fa-artstation",
            "fa-asymmetrik",
            "fa-atlassian",
            "fa-audible",
            "fa-autoprefixer",
            "fa-avianex",
            "fa-aviato",
            "fa-aws",
            "fa-bandcamp",
            "fa-battle-net",
            "fa-behance",
            "fa-behance-square",
            "fa-bimobject",
            "fa-bitbucket",
            "fa-bitcoin",
            "fa-bity",
            "fa-black-tie",
            "fa-blackberry",
            "fa-blogger",
            "fa-blogger-b",
            "fa-bluetooth",
            "fa-bluetooth-b",
            "fa-bootstrap",
            "fa-btc",
            "fa-buffer",
            "fa-buromobelexperte",
            "fa-buy-n-large",
            "fa-buysellads",
            "fa-canadian-maple-leaf",
            "fa-cc-amazon-pay",
            "fa-cc-amex",
            "fa-cc-apple-pay",
            "fa-cc-diners-club",
            "fa-cc-discover",
            "fa-cc-jcb",
            "fa-cc-mastercard",
            "fa-cc-paypal",
            "fa-cc-stripe",
            "fa-cc-visa",
            "fa-centercode",
            "fa-centos",
            "fa-chrome",
            "fa-chromecast",
            "fa-cloudscale",
            "fa-cloudsmith",
            "fa-cloudversify",
            "fa-codepen",
            "fa-codiepie",
            "fa-confluence",
            "fa-connectdevelop",
            "fa-contao",
            "fa-cotton-bureau",
            "fa-cpanel",
            "fa-creative-commons",
            "fa-creative-commons-by",
            "fa-creative-commons-nc",
            "fa-creative-commons-nc-eu",
            "fa-creative-commons-nc-jp",
            "fa-creative-commons-nd",
            "fa-creative-commons-pd",
            "fa-creative-commons-pd-alt",
            "fa-creative-commons-remix",
            "fa-creative-commons-sa",
            "fa-creative-commons-sampling",
            "fa-creative-commons-sampling-plus",
            "fa-creative-commons-share",
            "fa-creative-commons-zero",
            "fa-critical-role",
            "fa-css3",
            "fa-css3-alt",
            "fa-cuttlefish",
            "fa-d-and-d",
            "fa-d-and-d-beyond",
            "fa-dashcube",
            "fa-delicious",
            "fa-deploydog",
            "fa-deskpro",
            "fa-dev",
            "fa-deviantart",
            "fa-dhl",
            "fa-diaspora",
            "fa-digg",
            "fa-digital-ocean",
            "fa-discord",
            "fa-discourse",
            "fa-dochub",
            "fa-docker",
            "fa-draft2digital",
            "fa-dribbble",
            "fa-dribbble-square",
            "fa-dropbox",
            "fa-drupal",
            "fa-dyalog",
            "fa-earlybirds",
            "fa-ebay",
            "fa-edge",
            "fa-elementor",
            "fa-ello",
            "fa-ember",
            "fa-empire",
            "fa-envira",
            "fa-erlang",
            "fa-ethereum",
            "fa-etsy",
            "fa-evernote",
            "fa-expeditedssl",
            "fa-facebook",
            "fa-facebook-f",
            "fa-facebook-messenger",
            "fa-facebook-square",
            "fa-fantasy-flight-games",
            "fa-fedex",
            "fa-fedora",
            "fa-figma",
            "fa-firefox",
            "fa-firefox-browser",
            "fa-first-order",
            "fa-first-order-alt",
            "fa-firstdraft",
            "fa-flickr",
            "fa-flipboard",
            "fa-fly",
            "fa-font-awesome",
            "fa-font-awesome-alt",
            "fa-font-awesome-flag",
            "fa-fonticons",
            "fa-fonticons-fi",
            "fa-fort-awesome",
            "fa-fort-awesome-alt",
            "fa-forumbee",
            "fa-foursquare",
            "fa-free-code-camp",
            "fa-freebsd",
            "fa-fulcrum",
            "fa-galactic-republic",
            "fa-galactic-senate",
            "fa-get-pocket",
            "fa-gg",
            "fa-gg-circle",
            "fa-git",
            "fa-git-alt",
            "fa-git-square",
            "fa-github",
            "fa-github-alt",
            "fa-github-square",
            "fa-gitkraken",
            "fa-gitlab",
            "fa-gitter",
            "fa-glide",
            "fa-glide-g",
            "fa-gofore",
            "fa-goodreads",
            "fa-goodreads-g",
            "fa-google",
            "fa-google-drive",
            "fa-google-play",
            "fa-google-plus",
            "fa-google-plus-g",
            "fa-google-plus-square",
            "fa-google-wallet",
            "fa-gratipay",
            "fa-grav",
            "fa-gripfire",
            "fa-grunt",
            "fa-gulp",
            "fa-hacker-news",
            "fa-hacker-news-square",
            "fa-hackerrank",
            "fa-hips",
            "fa-hire-a-helper",
            "fa-hooli",
            "fa-hornbill",
            "fa-hotjar",
            "fa-houzz",
            "fa-html5",
            "fa-hubspot",
            "fa-ideal",
            "fa-imdb",
            "fa-instagram",
            "fa-intercom",
            "fa-internet-explorer",
            "fa-invision",
            "fa-ioxhost",
            "fa-itch-io",
            "fa-itunes",
            "fa-itunes-note",
            "fa-java",
            "fa-jedi-order",
            "fa-jenkins",
            "fa-jira",
            "fa-joget",
            "fa-joomla",
            "fa-js",
            "fa-js-square",
            "fa-jsfiddle",
            "fa-kaggle",
            "fa-keybase",
            "fa-keycdn",
            "fa-kickstarter",
            "fa-kickstarter-k",
            "fa-korvue",
            "fa-laravel",
            "fa-lastfm",
            "fa-lastfm-square",
            "fa-leanpub",
            "fa-less",
            "fa-line",
            "fa-linkedin",
            "fa-linkedin-in",
            "fa-linode",
            "fa-linux",
            "fa-lyft",
            "fa-magento",
            "fa-mailchimp",
            "fa-mandalorian",
            "fa-markdown",
            "fa-mastodon",
            "fa-maxcdn",
            "fa-mdb",
            "fa-medapps",
            "fa-medium",
            "fa-medium-m",
            "fa-medrt",
            "fa-meetup",
            "fa-megaport",
            "fa-mendeley",
            "fa-microblog",
            "fa-microsoft",
            "fa-mix",
            "fa-mixcloud",
            "fa-mizuni",
            "fa-modx",
            "fa-monero",
            "fa-napster",
            "fa-neos",
            "fa-nimblr",
            "fa-node",
            "fa-node-js",
            "fa-npm",
            "fa-ns8",
            "fa-nutritionix",
            "fa-odnoklassniki",
            "fa-odnoklassniki-square",
            "fa-old-republic",
            "fa-opencart",
            "fa-openid",
            "fa-opera",
            "fa-optin-monster",
            "fa-orcid",
            "fa-osi",
            "fa-page4",
            "fa-pagelines",
            "fa-palfed",
            "fa-patreon",
            "fa-paypal",
            "fa-penny-arcade",
            "fa-periscope",
            "fa-phabricator",
            "fa-phoenix-framework",
            "fa-phoenix-squadron",
            "fa-php",
            "fa-pied-piper",
            "fa-pied-piper-alt",
            "fa-pied-piper-hat",
            "fa-pied-piper-pp",
            "fa-pied-piper-square",
            "fa-pinterest",
            "fa-pinterest-p",
            "fa-pinterest-square",
            "fa-playstation",
            "fa-product-hunt",
            "fa-pushed",
            "fa-python",
            "fa-qq",
            "fa-quinscape",
            "fa-quora",
            "fa-r-project",
            "fa-raspberry-pi",
            "fa-ravelry",
            "fa-react",
            "fa-reacteurope",
            "fa-readme",
            "fa-rebel",
            "fa-red-river",
            "fa-reddit",
            "fa-reddit-alien",
            "fa-reddit-square",
            "fa-redhat",
            "fa-renren",
            "fa-replyd",
            "fa-researchgate",
            "fa-resolving",
            "fa-rev",
            "fa-rocketchat",
            "fa-rockrms",
            "fa-safari",
            "fa-salesforce",
            "fa-sass",
            "fa-schlix",
            "fa-scribd",
            "fa-searchengin",
            "fa-sellcast",
            "fa-sellsy",
            "fa-servicestack",
            "fa-shirtsinbulk",
            "fa-shopware",
            "fa-simplybuilt",
            "fa-sistrix",
            "fa-sith",
            "fa-sketch",
            "fa-skyatlas",
            "fa-skype",
            "fa-slack",
            "fa-slack-hash",
            "fa-slideshare",
            "fa-snapchat",
            "fa-snapchat-ghost",
            "fa-snapchat-square",
            "fa-soundcloud",
            "fa-sourcetree",
            "fa-speakap",
            "fa-speaker-deck",
            "fa-spotify",
            "fa-squarespace",
            "fa-stack-exchange",
            "fa-stack-overflow",
            "fa-stackpath",
            "fa-staylinked",
            "fa-steam",
            "fa-steam-square",
            "fa-steam-symbol",
            "fa-sticker-mule",
            "fa-strava",
            "fa-stripe",
            "fa-stripe-s",
            "fa-studiovinari",
            "fa-stumbleupon",
            "fa-stumbleupon-circle",
            "fa-superpowers",
            "fa-supple",
            "fa-suse",
            "fa-swift",
            "fa-symfony",
            "fa-teamspeak",
            "fa-telegram",
            "fa-telegram-plane",
            "fa-tencent-weibo",
            "fa-the-red-yeti",
            "fa-themeco",
            "fa-themeisle",
            "fa-think-peaks",
            "fa-trade-federation",
            "fa-trello",
            "fa-tripadvisor",
            "fa-tumblr",
            "fa-tumblr-square",
            "fa-twitch",
            "fa-twitter",
            "fa-twitter-square",
            "fa-typo3",
            "fa-uber",
            "fa-ubuntu",
            "fa-uikit",
            "fa-umbraco",
            "fa-uniregistry",
            "fa-unity",
            "fa-untappd",
            "fa-ups",
            "fa-usb",
            "fa-usps",
            "fa-ussunnah",
            "fa-vaadin",
            "fa-viacoin",
            "fa-viadeo",
            "fa-viadeo-square",
            "fa-viber",
            "fa-vimeo",
            "fa-vimeo-square",
            "fa-vimeo-v",
            "fa-vine",
            "fa-vk",
            "fa-vnv",
            "fa-vuejs",
            "fa-waze",
            "fa-weebly",
            "fa-weibo",
            "fa-weixin",
            "fa-whatsapp",
            "fa-whatsapp-square",
            "fa-whmcs",
            "fa-wikipedia-w",
            "fa-windows",
            "fa-wix",
            "fa-wizards-of-the-coast",
            "fa-wolf-pack-battalion",
            "fa-wordpress",
            "fa-wordpress-simple",
            "fa-wpbeginner",
            "fa-wpexplorer",
            "fa-wpforms",
            "fa-wpressr",
            "fa-xbox",
            "fa-xing",
            "fa-xing-square",
            "fa-y-combinator",
            "fa-yahoo",
            "fa-yammer",
            "fa-yandex",
            "fa-yandex-international",
            "fa-yarn",
            "fa-yelp",
            "fa-yoast",
            "fa-youtube",
            "fa-youtube-square",
            "fa-zhihu" 
        );
                  
        $duotones = array( 
            "fa-abacus",
            "fa-acorn",
            "fa-ad",
            "fa-address-book",
            "fa-address-card",
            "fa-adjust",
            "fa-air-conditioner",
            "fa-air-freshener",
            "fa-alarm-clock",
            "fa-alarm-exclamation",
            "fa-alarm-plus",
            "fa-alarm-snooze",
            "fa-album",
            "fa-album-collection",
            "fa-alicorn",
            "fa-alien",
            "fa-alien-monster",
            "fa-align-center",
            "fa-align-justify",
            "fa-align-left",
            "fa-align-right",
            "fa-align-slash",
            "fa-allergies",
            "fa-ambulance",
            "fa-american-sign-language-interpreting",
            "fa-amp-guitar",
            "fa-analytics",
            "fa-anchor",
            "fa-angel",
            "fa-angle-double-down",
            "fa-angle-double-left",
            "fa-angle-double-right",
            "fa-angle-double-up",
            "fa-angle-down",
            "fa-angle-left",
            "fa-angle-right",
            "fa-angle-up",
            "fa-angry",
            "fa-ankh",
            "fa-apple-alt",
            "fa-apple-crate",
            "fa-archive",
            "fa-archway",
            "fa-arrow-alt-circle-down",
            "fa-arrow-alt-circle-left",
            "fa-arrow-alt-circle-right",
            "fa-arrow-alt-circle-up",
            "fa-arrow-alt-down",
            "fa-arrow-alt-from-bottom",
            "fa-arrow-alt-from-left",
            "fa-arrow-alt-from-right",
            "fa-arrow-alt-from-top",
            "fa-arrow-alt-left",
            "fa-arrow-alt-right",
            "fa-arrow-alt-square-down",
            "fa-arrow-alt-square-left",
            "fa-arrow-alt-square-right",
            "fa-arrow-alt-square-up",
            "fa-arrow-alt-to-bottom",
            "fa-arrow-alt-to-left",
            "fa-arrow-alt-to-right",
            "fa-arrow-alt-to-top",
            "fa-arrow-alt-up",
            "fa-arrow-circle-down",
            "fa-arrow-circle-left",
            "fa-arrow-circle-right",
            "fa-arrow-circle-up",
            "fa-arrow-down",
            "fa-arrow-from-bottom",
            "fa-arrow-from-left",
            "fa-arrow-from-right",
            "fa-arrow-from-top",
            "fa-arrow-left",
            "fa-arrow-right",
            "fa-arrow-square-down",
            "fa-arrow-square-left",
            "fa-arrow-square-right",
            "fa-arrow-square-up",
            "fa-arrow-to-bottom",
            "fa-arrow-to-left",
            "fa-arrow-to-right",
            "fa-arrow-to-top",
            "fa-arrow-up",
            "fa-arrows",
            "fa-arrows-alt",
            "fa-arrows-alt-h",
            "fa-arrows-alt-v",
            "fa-arrows-h",
            "fa-arrows-v",
            "fa-assistive-listening-systems",
            "fa-asterisk",
            "fa-at",
            "fa-atlas",
            "fa-atom",
            "fa-atom-alt",
            "fa-audio-description",
            "fa-award",
            "fa-axe",
            "fa-axe-battle",
            "fa-baby",
            "fa-baby-carriage",
            "fa-backpack",
            "fa-backspace",
            "fa-backward",
            "fa-bacon",
            "fa-badge",
            "fa-badge-check",
            "fa-badge-dollar",
            "fa-badge-percent",
            "fa-badge-sheriff",
            "fa-badger-honey",
            "fa-bags-shopping",
            "fa-bahai",
            "fa-balance-scale",
            "fa-balance-scale-left",
            "fa-balance-scale-right",
            "fa-ball-pile",
            "fa-ballot",
            "fa-ballot-check",
            "fa-ban",
            "fa-band-aid",
            "fa-banjo",
            "fa-barcode",
            "fa-barcode-alt",
            "fa-barcode-read",
            "fa-barcode-scan",
            "fa-bars",
            "fa-baseball",
            "fa-baseball-ball",
            "fa-basketball-ball",
            "fa-basketball-hoop",
            "fa-bat",
            "fa-bath",
            "fa-battery-bolt",
            "fa-battery-empty",
            "fa-battery-full",
            "fa-battery-half",
            "fa-battery-quarter",
            "fa-battery-slash",
            "fa-battery-three-quarters",
            "fa-bed",
            "fa-bed-alt",
            "fa-bed-bunk",
            "fa-bed-empty",
            "fa-beer",
            "fa-bell",
            "fa-bell-exclamation",
            "fa-bell-on",
            "fa-bell-plus",
            "fa-bell-school",
            "fa-bell-school-slash",
            "fa-bell-slash",
            "fa-bells",
            "fa-betamax",
            "fa-bezier-curve",
            "fa-bible",
            "fa-bicycle",
            "fa-biking",
            "fa-biking-mountain",
            "fa-binoculars",
            "fa-biohazard",
            "fa-birthday-cake",
            "fa-blanket",
            "fa-blender",
            "fa-blender-phone",
            "fa-blind",
            "fa-blinds",
            "fa-blinds-open",
            "fa-blinds-raised",
            "fa-blog",
            "fa-bold",
            "fa-bolt",
            "fa-bomb",
            "fa-bone",
            "fa-bone-break",
            "fa-bong",
            "fa-book",
            "fa-book-alt",
            "fa-book-dead",
            "fa-book-heart",
            "fa-book-medical",
            "fa-book-open",
            "fa-book-reader",
            "fa-book-spells",
            "fa-book-user",
            "fa-bookmark",
            "fa-books",
            "fa-books-medical",
            "fa-boombox",
            "fa-boot",
            "fa-booth-curtain",
            "fa-border-all",
            "fa-border-bottom",
            "fa-border-center-h",
            "fa-border-center-v",
            "fa-border-inner",
            "fa-border-left",
            "fa-border-none",
            "fa-border-outer",
            "fa-border-right",
            "fa-border-style",
            "fa-border-style-alt",
            "fa-border-top",
            "fa-bow-arrow",
            "fa-bowling-ball",
            "fa-bowling-pins",
            "fa-box",
            "fa-box-alt",
            "fa-box-ballot",
            "fa-box-check",
            "fa-box-fragile",
            "fa-box-full",
            "fa-box-heart",
            "fa-box-open",
            "fa-box-up",
            "fa-box-usd",
            "fa-boxes",
            "fa-boxes-alt",
            "fa-boxing-glove",
            "fa-brackets",
            "fa-brackets-curly",
            "fa-braille",
            "fa-brain",
            "fa-bread-loaf",
            "fa-bread-slice",
            "fa-briefcase",
            "fa-briefcase-medical",
            "fa-bring-forward",
            "fa-bring-front",
            "fa-broadcast-tower",
            "fa-broom",
            "fa-browser",
            "fa-brush",
            "fa-bug",
            "fa-building",
            "fa-bullhorn",
            "fa-bullseye",
            "fa-bullseye-arrow",
            "fa-bullseye-pointer",
            "fa-burger-soda",
            "fa-burn",
            "fa-burrito",
            "fa-bus",
            "fa-bus-alt",
            "fa-bus-school",
            "fa-business-time",
            "fa-cabinet-filing",
            "fa-cactus",
            "fa-calculator",
            "fa-calculator-alt",
            "fa-calendar",
            "fa-calendar-alt",
            "fa-calendar-check",
            "fa-calendar-day",
            "fa-calendar-edit",
            "fa-calendar-exclamation",
            "fa-calendar-minus",
            "fa-calendar-plus",
            "fa-calendar-star",
            "fa-calendar-times",
            "fa-calendar-week",
            "fa-camcorder",
            "fa-camera",
            "fa-camera-alt",
            "fa-camera-home",
            "fa-camera-movie",
            "fa-camera-polaroid",
            "fa-camera-retro",
            "fa-campfire",
            "fa-campground",
            "fa-candle-holder",
            "fa-candy-cane",
            "fa-candy-corn",
            "fa-cannabis",
            "fa-capsules",
            "fa-car",
            "fa-car-alt",
            "fa-car-battery",
            "fa-car-building",
            "fa-car-bump",
            "fa-car-bus",
            "fa-car-crash",
            "fa-car-garage",
            "fa-car-mechanic",
            "fa-car-side",
            "fa-car-tilt",
            "fa-car-wash",
            "fa-caravan",
            "fa-caravan-alt",
            "fa-caret-circle-down",
            "fa-caret-circle-left",
            "fa-caret-circle-right",
            "fa-caret-circle-up",
            "fa-caret-down",
            "fa-caret-left",
            "fa-caret-right",
            "fa-caret-square-down",
            "fa-car" 
        );
                  
        $lights = array( 
            "fa-abacus",
            "fa-acorn",
            "fa-ad",
            "fa-address-book",
            "fa-address-card",
            "fa-adjust",
            "fa-air-conditioner",
            "fa-air-freshener",
            "fa-alarm-clock",
            "fa-alarm-exclamation",
            "fa-alarm-plus",
            "fa-alarm-snooze",
            "fa-album",
            "fa-album-collection",
            "fa-alicorn",
            "fa-alien",
            "fa-alien-monster",
            "fa-align-center",
            "fa-align-justify",
            "fa-align-left",
            "fa-align-right",
            "fa-align-slash",
            "fa-allergies",
            "fa-ambulance",
            "fa-american-sign-language-interpreting",
            "fa-amp-guitar",
            "fa-analytics",
            "fa-anchor",
            "fa-angel",
            "fa-angle-double-down",
            "fa-angle-double-left",
            "fa-angle-double-right",
            "fa-angle-double-up",
            "fa-angle-down",
            "fa-angle-left",
            "fa-angle-right",
            "fa-angle-up",
            "fa-angry",
            "fa-ankh",
            "fa-apple-alt",
            "fa-apple-crate",
            "fa-archive",
            "fa-archway",
            "fa-arrow-alt-circle-down",
            "fa-arrow-alt-circle-left",
            "fa-arrow-alt-circle-right",
            "fa-arrow-alt-circle-up",
            "fa-arrow-alt-down",
            "fa-arrow-alt-from-bottom",
            "fa-arrow-alt-from-left",
            "fa-arrow-alt-from-right",
            "fa-arrow-alt-from-top",
            "fa-arrow-alt-left",
            "fa-arrow-alt-right",
            "fa-arrow-alt-square-down",
            "fa-arrow-alt-square-left",
            "fa-arrow-alt-square-right",
            "fa-arrow-alt-square-up",
            "fa-arrow-alt-to-bottom",
            "fa-arrow-alt-to-left",
            "fa-arrow-alt-to-right",
            "fa-arrow-alt-to-top",
            "fa-arrow-alt-up",
            "fa-arrow-circle-down",
            "fa-arrow-circle-left",
            "fa-arrow-circle-right",
            "fa-arrow-circle-up",
            "fa-arrow-down",
            "fa-arrow-from-bottom",
            "fa-arrow-from-left",
            "fa-arrow-from-right",
            "fa-arrow-from-top",
            "fa-arrow-left",
            "fa-arrow-right",
            "fa-arrow-square-down",
            "fa-arrow-square-left",
            "fa-arrow-square-right",
            "fa-arrow-square-up",
            "fa-arrow-to-bottom",
            "fa-arrow-to-left",
            "fa-arrow-to-right",
            "fa-arrow-to-top",
            "fa-arrow-up",
            "fa-arrows",
            "fa-arrows-alt",
            "fa-arrows-alt-h",
            "fa-arrows-alt-v",
            "fa-arrows-h",
            "fa-arrows-v",
            "fa-assistive-listening-systems",
            "fa-asterisk",
            "fa-at",
            "fa-atlas",
            "fa-atom",
            "fa-atom-alt",
            "fa-audio-description",
            "fa-award",
            "fa-axe",
            "fa-axe-battle",
            "fa-baby",
            "fa-baby-carriage",
            "fa-backpack",
            "fa-backspace",
            "fa-backward",
            "fa-bacon",
            "fa-badge",
            "fa-badge-check",
            "fa-badge-dollar",
            "fa-badge-percent",
            "fa-badge-sheriff",
            "fa-badger-honey",
            "fa-bags-shopping",
            "fa-bahai",
            "fa-balance-scale",
            "fa-balance-scale-left",
            "fa-balance-scale-right",
            "fa-ball-pile",
            "fa-ballot",
            "fa-ballot-check",
            "fa-ban",
            "fa-band-aid",
            "fa-banjo",
            "fa-barcode",
            "fa-barcode-alt",
            "fa-barcode-read",
            "fa-barcode-scan",
            "fa-bars",
            "fa-baseball",
            "fa-baseball-ball",
            "fa-basketball-ball",
            "fa-basketball-hoop",
            "fa-bat",
            "fa-bath",
            "fa-battery-bolt",
            "fa-battery-empty",
            "fa-battery-full",
            "fa-battery-half",
            "fa-battery-quarter",
            "fa-battery-slash",
            "fa-battery-three-quarters",
            "fa-bed",
            "fa-bed-alt",
            "fa-bed-bunk",
            "fa-bed-empty",
            "fa-beer",
            "fa-bell",
            "fa-bell-exclamation",
            "fa-bell-on",
            "fa-bell-plus",
            "fa-bell-school",
            "fa-bell-school-slash",
            "fa-bell-slash",
            "fa-bells",
            "fa-betamax",
            "fa-bezier-curve",
            "fa-bible",
            "fa-bicycle",
            "fa-biking",
            "fa-biking-mountain",
            "fa-binoculars",
            "fa-biohazard",
            "fa-birthday-cake",
            "fa-blanket",
            "fa-blender",
            "fa-blender-phone",
            "fa-blind",
            "fa-blinds",
            "fa-blinds-open",
            "fa-blinds-raised",
            "fa-blog",
            "fa-bold",
            "fa-bolt",
            "fa-bomb",
            "fa-bone",
            "fa-bone-break",
            "fa-bong",
            "fa-book",
            "fa-book-alt",
            "fa-book-dead",
            "fa-book-heart",
            "fa-book-medical",
            "fa-book-open",
            "fa-book-reader",
            "fa-book-spells",
            "fa-book-user",
            "fa-bookmark",
            "fa-books",
            "fa-books-medical",
            "fa-boombox",
            "fa-boot",
            "fa-booth-curtain",
            "fa-border-all",
            "fa-border-bottom",
            "fa-border-center-h",
            "fa-border-center-v",
            "fa-border-inner",
            "fa-border-left",
            "fa-border-none",
            "fa-border-outer",
            "fa-border-right",
            "fa-border-style",
            "fa-border-style-alt",
            "fa-border-top",
            "fa-bow-arrow",
            "fa-bowling-ball",
            "fa-bowling-pins",
            "fa-box",
            "fa-box-alt",
            "fa-box-ballot",
            "fa-box-check",
            "fa-box-fragile",
            "fa-box-full",
            "fa-box-heart",
            "fa-box-open",
            "fa-box-up",
            "fa-box-usd",
            "fa-boxes",
            "fa-boxes-alt",
            "fa-boxing-glove",
            "fa-brackets",
            "fa-brackets-curly",
            "fa-braille",
            "fa-brain",
            "fa-bread-loaf",
            "fa-bread-slice",
            "fa-briefcase",
            "fa-briefcase-medical",
            "fa-bring-forward",
            "fa-bring-front",
            "fa-broadcast-tower",
            "fa-broom",
            "fa-browser",
            "fa-brush",
            "fa-bug",
            "fa-building",
            "fa-bullhorn",
            "fa-bullseye",
            "fa-bullseye-arrow",
            "fa-bullseye-pointer",
            "fa-burger-soda",
            "fa-burn",
            "fa-burrito",
            "fa-bus",
            "fa-bus-alt",
            "fa-bus-school",
            "fa-business-time",
            "fa-cabinet-filing",
            "fa-cactus",
            "fa-calculator",
            "fa-calculator-alt",
            "fa-calendar",
            "fa-calendar-alt",
            "fa-calendar-check",
            "fa-calendar-day",
            "fa-calendar-edit",
            "fa-calendar-exclamation",
            "fa-calendar-minus",
            "fa-calendar-plus",
            "fa-calendar-star",
            "fa-calendar-times",
            "fa-calendar-week",
            "fa-camcorder",
            "fa-camera",
            "fa-camera-alt",
            "fa-camera-home",
            "fa-camera-movie",
            "fa-camera-polaroid",
            "fa-camera-retro",
            "fa-campfire",
            "fa-campground",
            "fa-candle-holder",
            "fa-candy-cane",
            "fa-candy-corn",
            "fa-cannabis",
            "fa-capsules",
            "fa-car",
            "fa-car-alt",
            "fa-car-battery",
            "fa-car-building",
            "fa-car-bump",
            "fa-car-bus",
            "fa-car-crash",
            "fa-car-garage",
            "fa-car-mechanic",
            "fa-car-side",
            "fa-car-tilt",
            "fa-car-wash",
            "fa-caravan",
            "fa-caravan-alt",
            "fa-caret-circle-down",
            "fa-caret-circle-left",
            "fa-caret-circle-right",
            "fa-caret-circle-up",
            "fa-caret-down",
            "fa-caret-left",
            "fa-caret-right",
            "fa-caret-square-down",
            "fa-car" 
        );
        
        $regulars = array( 
            "fa-abacus",
            "fa-acorn",
            "fa-ad",
            "fa-address-book",
            "fa-address-card",
            "fa-adjust",
            "fa-air-conditioner",
            "fa-air-freshener",
            "fa-alarm-clock",
            "fa-alarm-exclamation",
            "fa-alarm-plus",
            "fa-alarm-snooze",
            "fa-album",
            "fa-album-collection",
            "fa-alicorn",
            "fa-alien",
            "fa-alien-monster",
            "fa-align-center",
            "fa-align-justify",
            "fa-align-left",
            "fa-align-right",
            "fa-align-slash",
            "fa-allergies",
            "fa-ambulance",
            "fa-american-sign-language-interpreting",
            "fa-amp-guitar",
            "fa-analytics",
            "fa-anchor",
            "fa-angel",
            "fa-angle-double-down",
            "fa-angle-double-left",
            "fa-angle-double-right",
            "fa-angle-double-up",
            "fa-angle-down",
            "fa-angle-left",
            "fa-angle-right",
            "fa-angle-up",
            "fa-angry",
            "fa-ankh",
            "fa-apple-alt",
            "fa-apple-crate",
            "fa-archive",
            "fa-archway",
            "fa-arrow-alt-circle-down",
            "fa-arrow-alt-circle-left",
            "fa-arrow-alt-circle-right",
            "fa-arrow-alt-circle-up",
            "fa-arrow-alt-down",
            "fa-arrow-alt-from-bottom",
            "fa-arrow-alt-from-left",
            "fa-arrow-alt-from-right",
            "fa-arrow-alt-from-top",
            "fa-arrow-alt-left",
            "fa-arrow-alt-right",
            "fa-arrow-alt-square-down",
            "fa-arrow-alt-square-left",
            "fa-arrow-alt-square-right",
            "fa-arrow-alt-square-up",
            "fa-arrow-alt-to-bottom",
            "fa-arrow-alt-to-left",
            "fa-arrow-alt-to-right",
            "fa-arrow-alt-to-top",
            "fa-arrow-alt-up",
            "fa-arrow-circle-down",
            "fa-arrow-circle-left",
            "fa-arrow-circle-right",
            "fa-arrow-circle-up",
            "fa-arrow-down",
            "fa-arrow-from-bottom",
            "fa-arrow-from-left",
            "fa-arrow-from-right",
            "fa-arrow-from-top",
            "fa-arrow-left",
            "fa-arrow-right",
            "fa-arrow-square-down",
            "fa-arrow-square-left",
            "fa-arrow-square-right",
            "fa-arrow-square-up",
            "fa-arrow-to-bottom",
            "fa-arrow-to-left",
            "fa-arrow-to-right",
            "fa-arrow-to-top",
            "fa-arrow-up",
            "fa-arrows",
            "fa-arrows-alt",
            "fa-arrows-alt-h",
            "fa-arrows-alt-v",
            "fa-arrows-h",
            "fa-arrows-v",
            "fa-assistive-listening-systems",
            "fa-asterisk",
            "fa-at",
            "fa-atlas",
            "fa-atom",
            "fa-atom-alt",
            "fa-audio-description",
            "fa-award",
            "fa-axe",
            "fa-axe-battle",
            "fa-baby",
            "fa-baby-carriage",
            "fa-backpack",
            "fa-backspace",
            "fa-backward",
            "fa-bacon",
            "fa-badge",
            "fa-badge-check",
            "fa-badge-dollar",
            "fa-badge-percent",
            "fa-badge-sheriff",
            "fa-badger-honey",
            "fa-bags-shopping",
            "fa-bahai",
            "fa-balance-scale",
            "fa-balance-scale-left",
            "fa-balance-scale-right",
            "fa-ball-pile",
            "fa-ballot",
            "fa-ballot-check",
            "fa-ban",
            "fa-band-aid",
            "fa-banjo",
            "fa-barcode",
            "fa-barcode-alt",
            "fa-barcode-read",
            "fa-barcode-scan",
            "fa-bars",
            "fa-baseball",
            "fa-baseball-ball",
            "fa-basketball-ball",
            "fa-basketball-hoop",
            "fa-bat",
            "fa-bath",
            "fa-battery-bolt",
            "fa-battery-empty",
            "fa-battery-full",
            "fa-battery-half",
            "fa-battery-quarter",
            "fa-battery-slash",
            "fa-battery-three-quarters",
            "fa-bed",
            "fa-bed-alt",
            "fa-bed-bunk",
            "fa-bed-empty",
            "fa-beer",
            "fa-bell",
            "fa-bell-exclamation",
            "fa-bell-on",
            "fa-bell-plus",
            "fa-bell-school",
            "fa-bell-school-slash",
            "fa-bell-slash",
            "fa-bells",
            "fa-betamax",
            "fa-bezier-curve",
            "fa-bible",
            "fa-bicycle",
            "fa-biking",
            "fa-biking-mountain",
            "fa-binoculars",
            "fa-biohazard",
            "fa-birthday-cake",
            "fa-blanket",
            "fa-blender",
            "fa-blender-phone",
            "fa-blind",
            "fa-blinds",
            "fa-blinds-open",
            "fa-blinds-raised",
            "fa-blog",
            "fa-bold",
            "fa-bolt",
            "fa-bomb",
            "fa-bone",
            "fa-bone-break",
            "fa-bong",
            "fa-book",
            "fa-book-alt",
            "fa-book-dead",
            "fa-book-heart",
            "fa-book-medical",
            "fa-book-open",
            "fa-book-reader",
            "fa-book-spells",
            "fa-book-user",
            "fa-bookmark",
            "fa-books",
            "fa-books-medical",
            "fa-boombox",
            "fa-boot",
            "fa-booth-curtain",
            "fa-border-all",
            "fa-border-bottom",
            "fa-border-center-h",
            "fa-border-center-v",
            "fa-border-inner",
            "fa-border-left",
            "fa-border-none",
            "fa-border-outer",
            "fa-border-right",
            "fa-border-style",
            "fa-border-style-alt",
            "fa-border-top",
            "fa-bow-arrow",
            "fa-bowling-ball",
            "fa-bowling-pins",
            "fa-box",
            "fa-box-alt",
            "fa-box-ballot",
            "fa-box-check",
            "fa-box-fragile",
            "fa-box-full",
            "fa-box-heart",
            "fa-box-open",
            "fa-box-up",
            "fa-box-usd",
            "fa-boxes",
            "fa-boxes-alt",
            "fa-boxing-glove",
            "fa-brackets",
            "fa-brackets-curly",
            "fa-braille",
            "fa-brain",
            "fa-bread-loaf",
            "fa-bread-slice",
            "fa-briefcase",
            "fa-briefcase-medical",
            "fa-bring-forward",
            "fa-bring-front",
            "fa-broadcast-tower",
            "fa-broom",
            "fa-browser",
            "fa-brush",
            "fa-bug",
            "fa-building",
            "fa-bullhorn",
            "fa-bullseye",
            "fa-bullseye-arrow",
            "fa-bullseye-pointer",
            "fa-burger-soda",
            "fa-burn",
            "fa-burrito",
            "fa-bus",
            "fa-bus-alt",
            "fa-bus-school",
            "fa-business-time",
            "fa-cabinet-filing",
            "fa-cactus",
            "fa-calculator",
            "fa-calculator-alt",
            "fa-calendar",
            "fa-calendar-alt",
            "fa-calendar-check",
            "fa-calendar-day",
            "fa-calendar-edit",
            "fa-calendar-exclamation",
            "fa-calendar-minus",
            "fa-calendar-plus",
            "fa-calendar-star",
            "fa-calendar-times",
            "fa-calendar-week",
            "fa-camcorder",
            "fa-camera",
            "fa-camera-alt",
            "fa-camera-home",
            "fa-camera-movie",
            "fa-camera-polaroid",
            "fa-camera-retro",
            "fa-campfire",
            "fa-campground",
            "fa-candle-holder",
            "fa-candy-cane",
            "fa-candy-corn",
            "fa-cannabis",
            "fa-capsules",
            "fa-car",
            "fa-car-alt",
            "fa-car-battery",
            "fa-car-building",
            "fa-car-bump",
            "fa-car-bus",
            "fa-car-crash",
            "fa-car-garage",
            "fa-car-mechanic",
            "fa-car-side",
            "fa-car-tilt",
            "fa-car-wash",
            "fa-caravan",
            "fa-caravan-alt",
            "fa-caret-circle-down",
            "fa-caret-circle-left",
            "fa-caret-circle-right",
            "fa-caret-circle-up",
            "fa-caret-down",
            "fa-caret-left",
            "fa-caret-right",
            "fa-caret-square-down",
            "fa-car" 
        );
        
        $solids = array( 
            "fa-abacus",
            "fa-acorn",
            "fa-ad",
            "fa-address-book",
            "fa-address-card",
            "fa-adjust",
            "fa-air-conditioner",
            "fa-air-freshener",
            "fa-alarm-clock",
            "fa-alarm-exclamation",
            "fa-alarm-plus",
            "fa-alarm-snooze",
            "fa-album",
            "fa-album-collection",
            "fa-alicorn",
            "fa-alien",
            "fa-alien-monster",
            "fa-align-center",
            "fa-align-justify",
            "fa-align-left",
            "fa-align-right",
            "fa-align-slash",
            "fa-allergies",
            "fa-ambulance",
            "fa-american-sign-language-interpreting",
            "fa-amp-guitar",
            "fa-analytics",
            "fa-anchor",
            "fa-angel",
            "fa-angle-double-down",
            "fa-angle-double-left",
            "fa-angle-double-right",
            "fa-angle-double-up",
            "fa-angle-down",
            "fa-angle-left",
            "fa-angle-right",
            "fa-angle-up",
            "fa-angry",
            "fa-ankh",
            "fa-apple-alt",
            "fa-apple-crate",
            "fa-archive",
            "fa-archway",
            "fa-arrow-alt-circle-down",
            "fa-arrow-alt-circle-left",
            "fa-arrow-alt-circle-right",
            "fa-arrow-alt-circle-up",
            "fa-arrow-alt-down",
            "fa-arrow-alt-from-bottom",
            "fa-arrow-alt-from-left",
            "fa-arrow-alt-from-right",
            "fa-arrow-alt-from-top",
            "fa-arrow-alt-left",
            "fa-arrow-alt-right",
            "fa-arrow-alt-square-down",
            "fa-arrow-alt-square-left",
            "fa-arrow-alt-square-right",
            "fa-arrow-alt-square-up",
            "fa-arrow-alt-to-bottom",
            "fa-arrow-alt-to-left",
            "fa-arrow-alt-to-right",
            "fa-arrow-alt-to-top",
            "fa-arrow-alt-up",
            "fa-arrow-circle-down",
            "fa-arrow-circle-left",
            "fa-arrow-circle-right",
            "fa-arrow-circle-up",
            "fa-arrow-down",
            "fa-arrow-from-bottom",
            "fa-arrow-from-left",
            "fa-arrow-from-right",
            "fa-arrow-from-top",
            "fa-arrow-left",
            "fa-arrow-right",
            "fa-arrow-square-down",
            "fa-arrow-square-left",
            "fa-arrow-square-right",
            "fa-arrow-square-up",
            "fa-arrow-to-bottom",
            "fa-arrow-to-left",
            "fa-arrow-to-right",
            "fa-arrow-to-top",
            "fa-arrow-up",
            "fa-arrows",
            "fa-arrows-alt",
            "fa-arrows-alt-h",
            "fa-arrows-alt-v",
            "fa-arrows-h",
            "fa-arrows-v",
            "fa-assistive-listening-systems",
            "fa-asterisk",
            "fa-at",
            "fa-atlas",
            "fa-atom",
            "fa-atom-alt",
            "fa-audio-description",
            "fa-award",
            "fa-axe",
            "fa-axe-battle",
            "fa-baby",
            "fa-baby-carriage",
            "fa-backpack",
            "fa-backspace",
            "fa-backward",
            "fa-bacon",
            "fa-badge",
            "fa-badge-check",
            "fa-badge-dollar",
            "fa-badge-percent",
            "fa-badge-sheriff",
            "fa-badger-honey",
            "fa-bags-shopping",
            "fa-bahai",
            "fa-balance-scale",
            "fa-balance-scale-left",
            "fa-balance-scale-right",
            "fa-ball-pile",
            "fa-ballot",
            "fa-ballot-check",
            "fa-ban",
            "fa-band-aid",
            "fa-banjo",
            "fa-barcode",
            "fa-barcode-alt",
            "fa-barcode-read",
            "fa-barcode-scan",
            "fa-bars",
            "fa-baseball",
            "fa-baseball-ball",
            "fa-basketball-ball",
            "fa-basketball-hoop",
            "fa-bat",
            "fa-bath",
            "fa-battery-bolt",
            "fa-battery-empty",
            "fa-battery-full",
            "fa-battery-half",
            "fa-battery-quarter",
            "fa-battery-slash",
            "fa-battery-three-quarters",
            "fa-bed",
            "fa-bed-alt",
            "fa-bed-bunk",
            "fa-bed-empty",
            "fa-beer",
            "fa-bell",
            "fa-bell-exclamation",
            "fa-bell-on",
            "fa-bell-plus",
            "fa-bell-school",
            "fa-bell-school-slash",
            "fa-bell-slash",
            "fa-bells",
            "fa-betamax",
            "fa-bezier-curve",
            "fa-bible",
            "fa-bicycle",
            "fa-biking",
            "fa-biking-mountain",
            "fa-binoculars",
            "fa-biohazard",
            "fa-birthday-cake",
            "fa-blanket",
            "fa-blender",
            "fa-blender-phone",
            "fa-blind",
            "fa-blinds",
            "fa-blinds-open",
            "fa-blinds-raised",
            "fa-blog",
            "fa-bold",
            "fa-bolt",
            "fa-bomb",
            "fa-bone",
            "fa-bone-break",
            "fa-bong",
            "fa-book",
            "fa-book-alt",
            "fa-book-dead",
            "fa-book-heart",
            "fa-book-medical",
            "fa-book-open",
            "fa-book-reader",
            "fa-book-spells",
            "fa-book-user",
            "fa-bookmark",
            "fa-books",
            "fa-books-medical",
            "fa-boombox",
            "fa-boot",
            "fa-booth-curtain",
            "fa-border-all",
            "fa-border-bottom",
            "fa-border-center-h",
            "fa-border-center-v",
            "fa-border-inner",
            "fa-border-left",
            "fa-border-none",
            "fa-border-outer",
            "fa-border-right",
            "fa-border-style",
            "fa-border-style-alt",
            "fa-border-top",
            "fa-bow-arrow",
            "fa-bowling-ball",
            "fa-bowling-pins",
            "fa-box",
            "fa-box-alt",
            "fa-box-ballot",
            "fa-box-check",
            "fa-box-fragile",
            "fa-box-full",
            "fa-box-heart",
            "fa-box-open",
            "fa-box-up",
            "fa-box-usd",
            "fa-boxes",
            "fa-boxes-alt",
            "fa-boxing-glove",
            "fa-brackets",
            "fa-brackets-curly",
            "fa-braille",
            "fa-brain",
            "fa-bread-loaf",
            "fa-bread-slice",
            "fa-briefcase",
            "fa-briefcase-medical",
            "fa-bring-forward",
            "fa-bring-front",
            "fa-broadcast-tower",
            "fa-broom",
            "fa-browser",
            "fa-brush",
            "fa-bug",
            "fa-building",
            "fa-bullhorn",
            "fa-bullseye",
            "fa-bullseye-arrow",
            "fa-bullseye-pointer",
            "fa-burger-soda",
            "fa-burn",
            "fa-burrito",
            "fa-bus",
            "fa-bus-alt",
            "fa-bus-school",
            "fa-business-time",
            "fa-cabinet-filing",
            "fa-cactus",
            "fa-calculator",
            "fa-calculator-alt",
            "fa-calendar",
            "fa-calendar-alt",
            "fa-calendar-check",
            "fa-calendar-day",
            "fa-calendar-edit",
            "fa-calendar-exclamation",
            "fa-calendar-minus",
            "fa-calendar-plus",
            "fa-calendar-star",
            "fa-calendar-times",
            "fa-calendar-week",
            "fa-camcorder",
            "fa-camera",
            "fa-camera-alt",
            "fa-camera-home",
            "fa-camera-movie",
            "fa-camera-polaroid",
            "fa-camera-retro",
            "fa-campfire",
            "fa-campground",
            "fa-candle-holder",
            "fa-candy-cane",
            "fa-candy-corn",
            "fa-cannabis",
            "fa-capsules",
            "fa-car",
            "fa-car-alt",
            "fa-car-battery",
            "fa-car-building",
            "fa-car-bump",
            "fa-car-bus",
            "fa-car-crash",
            "fa-car-garage",
            "fa-car-mechanic",
            "fa-car-side",
            "fa-car-tilt",
            "fa-car-wash",
            "fa-caravan",
            "fa-caravan-alt",
            "fa-caret-circle-down",
            "fa-caret-circle-left",
            "fa-caret-circle-right",
            "fa-caret-circle-up",
            "fa-caret-down",
            "fa-caret-left",
            "fa-caret-right",
            "fa-caret-square-down",
            "fa-car" 
          );

          switch($type) {
                default:
                case "all": {
                    foreach($brands as $brand) {
                        $fa[] = "fab ".$brand;
                    }
                    foreach($duotones as $duotone) {
                        $fa[] = "fab ".$duotone;
                    }
                    foreach($lights as $light) {
                        $fa[] = "fab ".$light;
                    }
                    foreach($regulars as $regular) {
                        $fa[] = "fab ".$regular;
                    }
                    foreach($solids as $solid) {
                        $fa[] = "fab ".$solid;
                    }
                     break;
                }
                
                case "brands": {
                    $fa = $brands;
                    break;
                }
                
                case "duotone": {
                    $fa = $duotones;
                    break;
                }
                
                case "light": {
                    $fa = $lights;
                    break;
                }
                
                case "regular": {
                    $fa = $regulars;
                    break;
                }
                
                case "solid": {
                    $fa = $solids;
                    break;
            }
        }
          
        return $fa;
    }
}
// --------------------------------------------------------------------

if ( ! function_usable('icon_selector'))
{

    /**
     * Font Awesome icon selector
    */
    function icon_selector($version = "5", $selected = "", $class = "form-control", $type_5 = "all", $class_5 = "fa", $picker = true) 
    {           
        $pack = ($version == '5') ? font_awesome($type_5) : pass_icon(5);

        $rows = "\n<select name=\"icon\" class=\"$class\">\n";
        foreach($pack as $key => $icon) 
        {
            $icon_title = str_replace('fa-', '', $icon); 
            $icon_title = ucfirst(str_replace('-', ' ', $icon_title));
            $icon = (stripos($icon, "fab") !== false) ? $icon : "$class_5 $icon";

            $selected = ($selected === $icon)? ' selected="selected"' : ''; 

            $rows .= "\t<option value=\"$icon\"$selected>" . ($picker === true ? $icon : $icon_title) . "</option>\n";
        }

        $rows .= "</select> \n";

        return $rows;

        return font_awesome("brands");
    }
}